apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - argocd-cm.yaml
  - argocd-bootstrap.yaml
  - applicationset.yaml
  - sealed-secrets.yaml
  - local-path-provisioner.yaml
  - cloudflared.yaml
  ## - monitoring.yaml TODO: monitoring
